#!/bin/sh
set -eu

umask 077

PROFILE="${PLOINKY_PROFILE:-default}"
TLS_PREFIX="/etc/turnserver/tls"
SECRET_FILE="/run/webmeet-turn-secret/auth-secret"
MIN_PORT=20000
MAX_PORT=20127
PEER_RESOLVE_TIMEOUT_SECONDS=60

log() {
    printf '[turnServerAgent] %s\n' "$1"
}

fail() {
    printf '[turnServerAgent] ERROR: %s\n' "$1" >&2
    exit 1
}

is_valid_ipv4_strict() {
    ip="$1"
    old_ifs="$IFS"
    IFS='.'
    # shellcheck disable=SC2086
    set -- $ip
    IFS="$old_ifs"
    [ "$#" -eq 4 ] || return 1
    for octet in "$1" "$2" "$3" "$4"; do
        case "$octet" in
            0|[1-9]|[1-9][0-9]|[1-9][0-9][0-9])
                ;;
            *)
                return 1
                ;;
        esac
        [ "$octet" -le 255 ] || return 1
    done
}

is_valid_unicast_ipv4() {
    ip="$1"
    is_valid_ipv4_strict "$ip" || return 1
    old_ifs="$IFS"
    IFS='.'
    # shellcheck disable=SC2086
    set -- $ip
    IFS="$old_ifs"
    first="$1"
    second="$2"
    [ "$first" -ne 0 ] || return 1
    [ "$first" -ne 127 ] || return 1
    [ "$first" -lt 224 ] || return 1
    if [ "$first" -eq 169 ] && [ "$second" -eq 254 ]; then
        return 1
    fi
}

is_valid_dns_hostname() {
    value="$1"
    [ "${#value}" -le 253 ] || return 1
    printf '%s' "$value" \
        | grep -Eq '^([A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)*[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?$'
}

is_valid_public_dns_hostname() {
    value="$1"
    is_valid_dns_hostname "$value" || return 1
    case "$value" in
        *.*)
            ;;
        *)
            return 1
            ;;
    esac
    case "$value" in
        *[!0-9.]* )
            ;;
        *)
            return 1
            ;;
    esac
    lower="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
    case "$lower" in
        localhost|*.localhost|*.local)
            return 1
            ;;
    esac
}

validate_generated_hex_secret() {
    name="$1"
    value="$2"
    [ "${#value}" -eq 64 ] && printf '%s' "$value" | grep -Eq '^[0-9a-f]{64}$' \
        || fail "$name must be the 64-character lowercase hexadecimal value generated by Ploinky."
}

validate_bounded_positive_int() {
    name="$1"
    value="$2"
    maximum="$3"
    case "$value" in
        ''|*[!0-9]*)
            fail "$name must be a positive integer (got '$value')."
            ;;
    esac
    [ "${#value}" -le "${#maximum}" ] \
        || fail "$name must not exceed $maximum (got '$value')."
    [ "$value" -gt 0 ] || fail "$name must be greater than zero (got '$value')."
    [ "$value" -le "$maximum" ] \
        || fail "$name must not exceed $maximum (got '$value')."
}

normalize_exact_peer_ipv4() {
    raw="$1"
    case "$raw" in
        *,*)
            fail "WEBMEET_TURN_ALLOWED_PEER_IPS must contain exactly one IPv4 address matching WEBMEET_LIVEKIT_NODE_IP."
            ;;
        */*)
            normalized_ip="${raw%%/*}"
            prefix="${raw#*/}"
            [ "$prefix" = "32" ] \
                || fail "WEBMEET_TURN_ALLOWED_PEER_IPS must be an exact IPv4 host (/32), not '$raw'."
            ;;
        *)
            normalized_ip="$raw"
            ;;
    esac
    is_valid_ipv4_strict "$normalized_ip" \
        || fail "WEBMEET_TURN_ALLOWED_PEER_IPS must contain one exact IPv4 address; got '$raw'."
    printf '%s\n' "$normalized_ip"
}

resolve_single_peer_ipv4() {
    peer_host="$1"
    command -v getent >/dev/null 2>&1 \
        || fail "the pinned Coturn image is missing getent; cannot resolve WEBMEET_LIVEKIT_PEER_HOST safely"

    attempt=0
    while [ "$attempt" -lt "$PEER_RESOLVE_TIMEOUT_SECONDS" ]; do
        addresses="$(getent ahostsv4 "$peer_host" 2>/dev/null \
            | awk '{print $1}' \
            | sort -u \
            | sed '/^$/d' || true)"
        address_count="$(printf '%s\n' "$addresses" | sed '/^$/d' | wc -l | tr -d '[:space:]')"
        if [ "$address_count" = "1" ] && is_valid_ipv4_strict "$addresses"; then
            printf '%s\n' "$addresses"
            return 0
        fi
        attempt=$((attempt + 1))
        sleep 1
    done

    fail "WEBMEET_LIVEKIT_PEER_HOST '$peer_host' did not resolve to exactly one IPv4 address within ${PEER_RESOLVE_TIMEOUT_SECONDS}s."
}

validate_tls_path() {
    name="$1"
    value="$2"
    case "$value" in
        "${TLS_PREFIX}"/*)
            relative_path="${value#"${TLS_PREFIX}"/}"
            ;;
        *)
            fail "$name must live under ${TLS_PREFIX}; got '$value'."
            ;;
    esac
    case "$relative_path" in
        ''|.|..|../*|*/../*|*/..)
            fail "$name must identify a file below ${TLS_PREFIX}; got '$value'."
            ;;
    esac
    [ -f "$value" ] && [ -r "$value" ] \
        || fail "$name is not a readable regular file at '$value'."
}

[ ! -L "$SECRET_FILE" ] \
    || fail "TURN secret file cannot be a symlink"
[ -f "$SECRET_FILE" ] && [ -r "$SECRET_FILE" ] \
    || fail "TURN secret file is missing or unreadable at '$SECRET_FILE'"
[ "$(wc -l < "$SECRET_FILE" | tr -d '[:space:]')" = "1" ] \
    || fail "TURN secret file must contain exactly one line"
[ "$(wc -c < "$SECRET_FILE" | tr -d '[:space:]')" = "65" ] \
    || fail "TURN secret file must contain one 64-character secret"
IFS= read -r SECRET < "$SECRET_FILE" \
    || fail "could not read TURN secret file"
USER_QUOTA="${WEBMEET_TURN_USER_QUOTA:-4}"
TOTAL_QUOTA="${WEBMEET_TURN_TOTAL_QUOTA:-100}"
MAX_BPS="${WEBMEET_TURN_MAX_BPS:-2000000}"
BPS_CAPACITY="${WEBMEET_TURN_BPS_CAPACITY:-50000000}"
UNAUTHORIZED_RPS="${WEBMEET_TURN_UNAUTHORIZED_RPS:-10}"
MAX_ALLOCATE_LIFETIME="${WEBMEET_TURN_MAX_ALLOCATION_LIFETIME_SECONDS:-3600}"
NONCE_LIFETIME="${WEBMEET_TURN_NONCE_LIFETIME_SECONDS:-600}"

validate_generated_hex_secret WEBMEET_TURN_AUTH_SECRET "$SECRET"
validate_bounded_positive_int WEBMEET_TURN_USER_QUOTA "$USER_QUOTA" 10000
validate_bounded_positive_int WEBMEET_TURN_TOTAL_QUOTA "$TOTAL_QUOTA" 100000
validate_bounded_positive_int WEBMEET_TURN_MAX_BPS "$MAX_BPS" 1000000000
validate_bounded_positive_int WEBMEET_TURN_BPS_CAPACITY "$BPS_CAPACITY" 2000000000
validate_bounded_positive_int WEBMEET_TURN_UNAUTHORIZED_RPS "$UNAUTHORIZED_RPS" 100000
validate_bounded_positive_int WEBMEET_TURN_MAX_ALLOCATION_LIFETIME_SECONDS "$MAX_ALLOCATE_LIFETIME" 86400
validate_bounded_positive_int WEBMEET_TURN_NONCE_LIFETIME_SECONDS "$NONCE_LIFETIME" 86400
[ "$TOTAL_QUOTA" -ge "$USER_QUOTA" ] \
    || fail "WEBMEET_TURN_TOTAL_QUOTA must be greater than or equal to WEBMEET_TURN_USER_QUOTA."
[ "$BPS_CAPACITY" -ge "$MAX_BPS" ] \
    || fail "WEBMEET_TURN_BPS_CAPACITY must be greater than or equal to WEBMEET_TURN_MAX_BPS."

case "$PROFILE" in
    default|dev)
        TURN_HOST="${WEBMEET_TURN_HOST:-127.0.0.1}"
        TURN_REALM="webmeet.local"
        PEER_HOST="${WEBMEET_LIVEKIT_PEER_HOST:-livekitserveragent}"
        is_valid_dns_hostname "$PEER_HOST" \
            || fail "WEBMEET_LIVEKIT_PEER_HOST must be a DNS hostname; got '$PEER_HOST'."
        PEER_IP="$(resolve_single_peer_ipv4 "$PEER_HOST")"
        TLS_CERT=""
        TLS_KEY=""
        EXTERNAL_IP=""
        ;;
    prod)
        TURN_HOST="${WEBMEET_TURN_HOST:?WEBMEET_TURN_HOST is required in the prod profile}"
        TURN_REALM="$TURN_HOST"
        NODE_IP="${WEBMEET_LIVEKIT_NODE_IP:?WEBMEET_LIVEKIT_NODE_IP is required in the prod profile}"
        ALLOWED_PEERS="${WEBMEET_TURN_ALLOWED_PEER_IPS:?WEBMEET_TURN_ALLOWED_PEER_IPS is required in the prod profile}"
        EXTERNAL_IP="${WEBMEET_TURN_EXTERNAL_IP:?WEBMEET_TURN_EXTERNAL_IP is required in the prod profile}"
        TLS_CERT="${WEBMEET_TURN_TLS_CERT_PATH:-/etc/turnserver/tls/fullchain.pem}"
        TLS_KEY="${WEBMEET_TURN_TLS_KEY_PATH:-/etc/turnserver/tls/privkey.pem}"

        is_valid_public_dns_hostname "$TURN_HOST" \
            || fail "WEBMEET_TURN_HOST must be a public multi-label DNS hostname (not an IP literal, localhost, or .local name); got '$TURN_HOST'."
        is_valid_unicast_ipv4 "$NODE_IP" \
            || fail "WEBMEET_LIVEKIT_NODE_IP must be a unicast IPv4 address (not unspecified, loopback, link-local, or multicast); got '$NODE_IP'."
        PEER_IP="$(normalize_exact_peer_ipv4 "$ALLOWED_PEERS")"
        [ "$PEER_IP" = "$NODE_IP" ] \
            || fail "WEBMEET_TURN_ALLOWED_PEER_IPS must equal WEBMEET_LIVEKIT_NODE_IP exactly."
        is_valid_unicast_ipv4 "$EXTERNAL_IP" \
            || fail "WEBMEET_TURN_EXTERNAL_IP must be a unicast IPv4 address (not unspecified, loopback, link-local, or multicast); got '$EXTERNAL_IP'."
        validate_tls_path WEBMEET_TURN_TLS_CERT_PATH "$TLS_CERT"
        validate_tls_path WEBMEET_TURN_TLS_KEY_PATH "$TLS_KEY"
        ;;
    *)
        fail "unknown PLOINKY_PROFILE '$PROFILE'."
        ;;
esac

RUNTIME_DIR="$(mktemp -d /tmp/turnserver-agent.XXXXXX)" \
    || fail "could not create a private runtime directory"
CONFIG_FILE="${RUNTIME_DIR}/turnserver.conf"

{
    printf 'use-auth-secret\n'
    printf 'static-auth-secret=%s\n' "$SECRET"
    printf 'fingerprint\n'
    printf 'no-multicast-peers\n'
    printf 'realm=%s\n' "$TURN_REALM"
    # A single IPv4 wildcard listener prevents Coturn from discovering and
    # binding IPv6 interfaces. With no relay-ip override, allocations use the
    # IPv4 listener address family; IPv6 peers are also denied below.
    printf 'listening-ip=0.0.0.0\n'
    printf 'listening-port=3478\n'
    printf 'min-port=%s\n' "$MIN_PORT"
    printf 'max-port=%s\n' "$MAX_PORT"
    printf 'user-quota=%s\n' "$USER_QUOTA"
    printf 'total-quota=%s\n' "$TOTAL_QUOTA"
    printf 'max-bps=%s\n' "$MAX_BPS"
    printf 'bps-capacity=%s\n' "$BPS_CAPACITY"
    printf 'stale-nonce=%s\n' "$NONCE_LIFETIME"
    printf 'max-allocate-lifetime=%s\n' "$MAX_ALLOCATE_LIFETIME"
    printf 'unauthorized-ratelimit\n'
    printf 'unauthorized-ratelimit-rps=%s\n' "$UNAUTHORIZED_RPS"
    printf 'log-file=stdout\n'
    printf 'pidfile=/tmp/turnserver.pid\n'
    # Coturn gives explicit allows precedence over denies. Deny the complete
    # IPv4 and IPv6 spaces, then allow exactly the canonical LiveKit peer.
    printf 'denied-peer-ip=0.0.0.0-255.255.255.255\n'
    printf 'denied-peer-ip=::-ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff\n'
    printf 'allowed-peer-ip=%s\n' "$PEER_IP"
} > "$CONFIG_FILE"

if [ "$PROFILE" = "prod" ]; then
    {
        printf 'external-ip=%s\n' "$EXTERNAL_IP"
        printf 'cert=%s\n' "$TLS_CERT"
        printf 'pkey=%s\n' "$TLS_KEY"
        printf 'tls-listening-port=5349\n'
        printf 'no-dtls\n'
    } >> "$CONFIG_FILE"
else
    {
        printf 'no-tls\n'
        printf 'no-dtls\n'
    } >> "$CONFIG_FILE"
fi

chmod 0600 "$CONFIG_FILE"
printf '%s\n' "$PEER_IP" > /tmp/turnserver-peer-ip
chmod 0600 /tmp/turnserver-peer-ip
rm -f /tmp/turnserver.pid
log "starting Coturn with an exclusive peer policy for profile '$PROFILE'"
unset SECRET
exec env -u WEBMEET_TURN_AUTH_SECRET turnserver -c "$CONFIG_FILE"
